(* ::Package:: *)

(* ::Input:: *)
(*experiments={*)
(*"EYrainbow_glucose",*)
(*"EYrainbow_glucose_largerBF",*)
(*"EYrainbow_rapamycin_1stTry",*)
(*"EYrainbow_rapamycin_CheckBistability",*)
(*"EYrainbow_1nmpp1_1st",*)
(*"EYrainbow_leucine_large",*)
(*"EYrainbowWhi5Up_betaEstrodiol"*)
(*};*)
(*data = Import[FileNameJoin[{NotebookDirectory[],"fitCellSizeWithOrganelle.csv"}],"Data","HeaderLines"->1];*)
(*epsilon = 10^(-18);*)
(*filled = data/.{0.->epsilon};*)
(*washed = Select[data,Function[x,NoneTrue[x,#==0&]]];*)


(* ::Input:: *)
(*(* Check data *)*)
(*Position[filled,0.]*)
(*Position[washed,0.]*)


(* ::Input:: *)
(*Length[filled]*)
(*Length[washed]*)


(* ::Input:: *)
(*fitCellSizeFromOrganelles[dataset_,hasDiagonal_]:=Module[*)
(*{iEnd,jOffset,organelle,expr,a,b,c,alpha,beta,mean,mean0,n,n0,nu,sigma,nlm,params,fittedFunc,fitted,fittedMin,fittedMax,dataMin,dataMax},*)
(*organelle=Table[*)
(*alpha[i] ((n[i]-n0[i])^nu[i] )((mean[i]-mean0[i])^sigma[i])+beta[i],*)
(*{i,1,6}*)
(*];*)
(*iEnd=If[hasDiagonal,6,5];*)
(*jOffset = If[hasDiagonal,0,1];*)
(*expr = Sum[a[i]organelle[[i]],{i,1,6}]+Sum[organelle[[i]] b[i,j]organelle[[j]],{i,1,iEnd},{j,i+jOffset,6}]+c;*)
(*nlm = NonlinearModelFit[*)
(*dataset[[All,2;;]],expr,*)
(*Join[*)
(*Table[a[i],{i,1,6}],*)
(*Flatten[Table[b[i,j],{i,1,iEnd},{j,i+jOffset,6}]],*)
(*{c},*)
(*Table[alpha[i],{i,1,6}],*)
(*Table[n0[i],{i,1,6}],*)
(*Table[mean0[i],{i,1,6}],*)
(*Table[nu[i],{i,1,6}],*)
(*Table[sigma[i],{i,1,6}],*)
(*Table[beta[i],{i,1,6}]*)
(*],*)
(*Join[*)
(*Table[mean[i],{i,1,6}],*)
(*Table[n[i],{i,1,6}]*)
(*],*)
(*MaxIterations->\[Infinity]*)
(*];*)
(*params=nlm["BestFitParameters"];*)
(*Print["CellSize = Sum[a[i]*organalle[i]]+Sum[organelle[i]*b[i,j]*organelle[j]]+c"];*)
(*Print["a[i]: ",Table[a[i],{i,1,6}]/.params];*)
(*Print["b[i,j]: ",Table[b[i,j],{i,1,6},{j,1,6}]/.params//MatrixForm];*)
(*Print["c: ", c/.params];*)
(*Print["organalle = alpha*(n-n0)^nu*(mean-mean0)^sigma+beta"];*)
(*Print["alpha[i]: ",Table[alpha[i],{i,1,6}]/.params];*)
(*Print["n0[i]: ",Table[n0[i],{i,1,6}]/.params];*)
(*Print["mean0[i]: ",Table[mean0[i],{i,1,6}]/.params];*)
(*Print["nu[i]: ",Table[nu[i],{i,1,6}]/.params];*)
(*Print["sigma[i]: ",Table[sigma[i],{i,1,6}]/.params];*)
(*Print["beta[i]: ",Table[beta[i],{i,1,6}]/.params];*)
(*Print["Adjusted R Square: ", nlm["AdjustedRSquared"]];*)
(*Print["p\[Hyphen]values for parameter z\[Hyphen]statistics: ", nlm["ParameterPValues"]];*)
(*Print["t-statistics for parameter estimates: ", nlm["ParameterTStatistics"]];*)
(*fittedFunc = Function[*)
(*vec,*)
(*expr/.params*)
(*/.Table[n[i]->vec[[i]],{i,1,6}]*)
(*/.Table[mean[i]->vec[[i+6]],{i,1,6}]*)
(*];*)
(*fitted = Map[fittedFunc,dataset[[All,2;;-2]]];*)
(*fittedMin = Min[fitted];*)
(*fittedMax = Max[fitted];*)
(*dataMin = Min[dataset[[All,-1]]];*)
(*dataMax = Max[dataset[[All,-1]]];*)
(*Print[Show[*)
(*ListPlot[*)
(*Transpose[{dataset[[All,-1]],fitted}],*)
(*PlotTheme->"Scientific",AspectRatio->(fittedMax)/(dataMax)*)
(*],*)
(*Plot[x,{x,0,dataMax}]*)
(*]];*)
(*Print[""]*)
(*]*)


(* ::Input:: *)
(*Print["All Experiments, Null Organelles filled with 0:"];*)
(*fitCellSizeFromOrganelles[filled]*)


(* ::Input:: *)
(*Print["All Experiments, Null Organelles Excluded:"];*)
(*fitCellSizeFromOrganelles[washed];*)


(* ::Input:: *)
(*Do[*)
(*Print[experiments[[i]],", Null Organelles filled with 0:"];*)
(*fitCellSizeFromOrganelles[Select[filled,#[[1]]==experiments[[i]]&]];,*)
(*{i,1,Length[experiments]}*)
(*];*)


(* ::Input:: *)
(*Do[*)
(*Print[experiments[[i]],", Null Organelles Excluded:"];*)
(*fitCellSizeFromOrganelles[Select[washed,#[[1]]==experiments[[i]]&]];,*)
(*{i,1,Length[experiments]}*)
(*]*)



